### ISSUE TITLE
iOS pod "error: too many arguments to block call, expected 1, have 3"

### ISSUE THREAD

**Issue by sir-gon** [johanneslumpe/react-native-fs#194]
Using `"version": "2.0.1-rc.2"` from package.json, I'm getting this when I'm building from xcode:

```
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:103:30: error: too many arguments to block call, expected 1, have 3
    return reject(@"ENOENT", [NSString stringWithFormat:@"ENOENT: no such file or directory, open '%@'", filepath], nil);
           ~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:123:32: error: too many arguments to block call, expected 1, have 3
      return reject(@"ENOENT", [NSString stringWithFormat:@"ENOENT: no such file or directory, open '%@'", filepath], nil);
             ~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:137:42: warning: incompatible pointer types sending 'NSException *' to parameter of type 'NSError *' [-Wincompatible-pointer-types]
    return [self reject:reject withError:e];
                                         ^
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:431:67: note: passing argument to parameter 'error' here
- (void)reject:(RCTPromiseRejectBlock)reject withError:(NSError *)error
                                                                  ^
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:149:30: error: too many arguments to block call, expected 1, have 3
    return reject(@"ENOENT", [NSString stringWithFormat:@"ENOENT: no such file or directory, open '%@'", filepath], nil);
           ~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:197:30: error: too many arguments to block call, expected 1, have 3
    return reject(@"ENOENT", [NSString stringWithFormat:@"ENOENT: no such file or directory, open '%@'", filepath], nil);
           ~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:209:30: error: too many arguments to block call, expected 1, have 3
    return reject(@"EISDIR", @"EISDIR: illegal operation on a directory, read", nil);
           ~~~~~~            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/node_modules/react-native-fs/RNFSManager.m:434:26: error: too many arguments to block call, expected 1, have 3
  reject(codeWithDomain, error.localizedDescription, error);
  ~~~~~~                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 6 errors generated.

```

Then, I can't use this library.
Also, I'm having the weird dependency of "react 0.11.0" (#116) installing from cocoapods...

**Comment by arronmabrey** [comment]
I'm also having this same issue

**Comment by sir-gon** [comment]
I getting work this doing manual integration instead of cocoapods
I presume that the integration using cocoapods is completely outdated and does not work in current versions (0.35)

**Comment by wlaeri** [comment]
I can't get this to work using manual integration or cocoapods. Following the cocoapods installation instructions I get this 'too many arguments to block call' error  and using manual integration I get the referenced error #190

**Comment by SerzN1** [comment]
+1

**Comment by alexkendall** [comment]
+1

**Comment by alex-alex2006hw** [comment]
+1

**Comment by vu0tran** [comment]
+1

**Comment by panteparak** [comment]
Here is what I did to resolve this problem. My RN version is 0.55.4
Go to `iOS` folder within react-native project
`rm -rf Pods Podfile.lock`
`pod install`
clear watchman watches: `watchman watch-del-all`
Remove and reinstall node_modules: `rm -rf node_modules && npm install`
Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*`
Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`
