### ISSUE TITLE
.spread doesn't work in the last version (2.0.1-rc.2)

### ISSUE THREAD

**Issue by manask88** [johanneslumpe/react-native-fs#182]
fobar.spread doesn't work anymore

For example, I tried using:

  RNFS.mkdir(this._getFolder(), { NSURLIsExcludedFromBackupKey: true })
    .spread((isSuccessful, newFilePath) => {
     ...
    })

and got : spread is not a function.

I would like to know if this change is intended as I need to make lots of changes in my code if I really want to use the latest version of the library.

**Comment by johanneslumpe** [comment]
We got rid of the bluebird dependency and started using the promise interface provided by react native, so yes - this is expected.

**Comment by faceyspacey** [comment]
do you have to provide `NSURLIsExcludedFromBackupKey` or is it automatically supplied by default for iOS?
